// GENERATED by packages/studio-core/scripts/build-destinations.mjs — do not edit.
// Source: packages/cli/schema/channel-specs.json (verified 2026-08-04).
// Re-run the script and commit whenever the specs change; destinations.test.ts
// gates staleness on CHANNEL_SPECS_HASH.

/**
 * A destination is where a release's media goes — the output twin of the
 * doors registry's "a door is what you bring". One row per channel asset,
 * derived from the verified channel specs; `vos deliver` loops these and
 * the kit manifest records them.
 */
export interface Destination {
  /** `${channel}-${asset}` — the id `vos deliver --to` and kit.json use. */
  id: string
  channel: string
  asset: string
  label: string
  kind: 'video' | 'still' | 'still-set'
  /** Reduced aspect ratio, the exportSizeFor convention. */
  ratio: string
  px: { w: number; h: number }
  /** still-set only: how many the channel takes. */
  count?: { min: number; max: number }
  /**
   * Image genre: 'screenshot' = real UI from the take (store policy demands
   * real UX); 'card' = a COMPOSED cover — rendered from the maker's poster
   * program when `vos deliver --poster` has one.
   */
  genre?: 'screenshot' | 'card'
  minSeconds?: number
  maxSeconds?: number
  maxBytes?: number
  /** The format the kit renders. */
  format: 'mp4' | 'png'
  /** What the channel accepts, in the spec's own words. */
  accepts: string
  /** How footage meets an off-ratio frame (a still fills, a video letterboxes). */
  fit: 'contain' | 'cover'
  /**
   * The destination's word policy: 'none' = the picture carries it alone (a
   * tile, a store screenshot), 'allowed', 'expected' = a card that should
   * say something. The picture checks read it.
   */
  text: 'none' | 'allowed' | 'expected'
  /**
   * The rect, as fractions of the frame, every text box must sit inside:
   * the platform's own chrome or crop covers the rest.
   */
  safe: { x: number; y: number; w: number; h: number }
  notes: string
}

export const CHANNEL_SPECS_VERIFIED = '2026-08-04'

export const CHANNEL_SPECS_HASH =
  'e2382b03d59d01a5d7ed20c928e60fd53267a8038cf686a5ba21758f86e50cb9'

export const DESTINATIONS: Destination[] = [
  {
    id: 'youtube-main-demo',
    channel: 'youtube',
    asset: 'main-demo',
    label: 'YouTube demo',
    kind: 'video',
    ratio: '16:9',
    px: {
      w: 1920,
      h: 1080,
    },
    minSeconds: 60,
    maxSeconds: 120,
    format: 'mp4',
    accepts: 'mp4 (H.264+AAC)',
    fit: 'contain',
    text: 'allowed',
    safe: {
      x: 0.05,
      y: 0.08,
      w: 0.9,
      h: 0.84,
    },
    notes:
      'Captions burned in. The same public upload serves the Chrome Web Store promo video and Product Hunt video (both take YouTube URLs only).',
  },
  {
    id: 'x-feed-cut',
    channel: 'x',
    asset: 'feed-cut',
    label: 'X feed cut',
    kind: 'video',
    ratio: '16:9',
    px: {
      w: 1920,
      h: 1080,
    },
    minSeconds: 30,
    maxSeconds: 140,
    maxBytes: 536870912,
    format: 'mp4',
    accepts: 'mp4 (H.264+AAC ONLY — HEVC/VP9/AV1 rejected)',
    fit: 'contain',
    text: 'allowed',
    safe: {
      x: 0.05,
      y: 0.08,
      w: 0.9,
      h: 0.84,
    },
    notes:
      '30–60s plays best; 140s/512MB is the free-tier ceiling. 1:1 also allowed. Native upload, never a link post.',
  },
  {
    id: 'shorts-linkedin-vertical-cut',
    channel: 'shorts-linkedin',
    asset: 'vertical-cut',
    label: 'Shorts / LinkedIn vertical cut',
    kind: 'video',
    ratio: '9:16',
    px: {
      w: 1080,
      h: 1920,
    },
    minSeconds: 30,
    maxSeconds: 90,
    format: 'mp4',
    accepts: 'mp4 (H.264+AAC)',
    fit: 'contain',
    text: 'expected',
    safe: {
      x: 0.0833,
      y: 0.1979,
      w: 0.8333,
      h: 0.6042,
    },
    notes:
      'Critical text inside a centered ~900×1160 safe zone — platform chrome covers the rest. Serves YouTube Shorts and LinkedIn native vertical.',
  },
  {
    id: 'github-readme-loop',
    channel: 'github',
    asset: 'readme-loop',
    label: 'GitHub README loop',
    kind: 'video',
    ratio: '16:9',
    px: {
      w: 1920,
      h: 1080,
    },
    minSeconds: 10,
    maxSeconds: 20,
    maxBytes: 10485760,
    format: 'mp4',
    accepts: 'mp4 (H.264)',
    fit: 'contain',
    text: 'none',
    safe: {
      x: 0.05,
      y: 0.08,
      w: 0.9,
      h: 0.84,
    },
    notes:
      '≤10MB is the free-plan attachment ceiling; two-pass target bitrate from duration.',
  },
  {
    id: 'youtube-thumbnail',
    channel: 'youtube',
    asset: 'thumbnail',
    label: 'YouTube thumbnail',
    kind: 'still',
    ratio: '16:9',
    px: {
      w: 1280,
      h: 720,
    },
    genre: 'card',
    maxBytes: 2097152,
    format: 'png',
    accepts: 'png|jpg',
    fit: 'cover',
    text: 'expected',
    safe: {
      x: 0.05,
      y: 0.08,
      w: 0.9,
      h: 0.84,
    },
    notes: '',
  },
  {
    id: 'cws-screenshot',
    channel: 'cws',
    asset: 'screenshot',
    label: 'Chrome Web Store screenshot',
    kind: 'still-set',
    ratio: '8:5',
    px: {
      w: 1280,
      h: 800,
    },
    count: {
      min: 1,
      max: 5,
    },
    genre: 'screenshot',
    format: 'png',
    accepts: 'png|jpg',
    fit: 'cover',
    text: 'none',
    safe: {
      x: 0,
      y: 0,
      w: 1,
      h: 1,
    },
    notes:
      'Real UX only — misleading listing images are a removal-grade violation. Full bleed, square corners.',
  },
  {
    id: 'cws-small-promo-tile',
    channel: 'cws',
    asset: 'small-promo-tile',
    label: 'Chrome Web Store small promo tile',
    kind: 'still',
    ratio: '11:7',
    px: {
      w: 440,
      h: 280,
    },
    genre: 'card',
    format: 'png',
    accepts: 'png|jpg',
    fit: 'cover',
    text: 'none',
    safe: {
      x: 0,
      y: 0,
      w: 1,
      h: 1,
    },
    notes:
      'Listings without one rank lower. No text; fill the region; subject centered.',
  },
  {
    id: 'cws-marquee',
    channel: 'cws',
    asset: 'marquee',
    label: 'Chrome Web Store marquee',
    kind: 'still',
    ratio: '5:2',
    px: {
      w: 1400,
      h: 560,
    },
    genre: 'card',
    format: 'png',
    accepts: 'png|jpg',
    fit: 'cover',
    text: 'allowed',
    safe: {
      x: 0.05,
      y: 0.08,
      w: 0.9,
      h: 0.84,
    },
    notes: 'Carousel eligibility.',
  },
  {
    id: 'cws-icon',
    channel: 'cws',
    asset: 'icon',
    label: 'Chrome Web Store icon',
    kind: 'still',
    ratio: '1:1',
    px: {
      w: 128,
      h: 128,
    },
    format: 'png',
    accepts: 'png',
    fit: 'cover',
    text: 'none',
    safe: {
      x: 0,
      y: 0,
      w: 1,
      h: 1,
    },
    notes: '96×96 art + 16px transparent padding.',
  },
  {
    id: 'producthunt-thumbnail',
    channel: 'producthunt',
    asset: 'thumbnail',
    label: 'Product Hunt thumbnail',
    kind: 'still',
    ratio: '1:1',
    px: {
      w: 240,
      h: 240,
    },
    genre: 'card',
    maxBytes: 3145728,
    format: 'png',
    accepts: 'gif|png',
    fit: 'cover',
    text: 'none',
    safe: {
      x: 0.06,
      y: 0.06,
      w: 0.88,
      h: 0.88,
    },
    notes: 'GIF animates on hover only — the first frame must stand alone.',
  },
  {
    id: 'producthunt-gallery',
    channel: 'producthunt',
    asset: 'gallery',
    label: 'Product Hunt gallery',
    kind: 'still-set',
    ratio: '127:76',
    px: {
      w: 1270,
      h: 760,
    },
    count: {
      min: 4,
      max: 8,
    },
    genre: 'screenshot',
    format: 'png',
    accepts: 'png|jpg|gif',
    fit: 'cover',
    text: 'none',
    safe: {
      x: 0,
      y: 0,
      w: 1,
      h: 1,
    },
    notes: 'First image is the hero.',
  },
  {
    id: 'x-feed-image',
    channel: 'x',
    asset: 'feed-image',
    label: 'X feed image',
    kind: 'still',
    ratio: '16:9',
    px: {
      w: 1200,
      h: 675,
    },
    genre: 'card',
    format: 'png',
    accepts: 'png|jpg',
    fit: 'cover',
    text: 'allowed',
    safe: {
      x: 0.05,
      y: 0.08,
      w: 0.9,
      h: 0.84,
    },
    notes: '',
  },
  {
    id: 'linkedin-feed-image',
    channel: 'linkedin',
    asset: 'feed-image',
    label: 'LinkedIn feed image',
    kind: 'still',
    ratio: '400:209',
    px: {
      w: 1200,
      h: 627,
    },
    genre: 'card',
    format: 'png',
    accepts: 'png|jpg',
    fit: 'cover',
    text: 'expected',
    safe: {
      x: 0.05,
      y: 0.08,
      w: 0.9,
      h: 0.84,
    },
    notes: '1080×1350 vertical also performs in the mobile feed.',
  },
  {
    id: 'og-card',
    channel: 'og',
    asset: 'card',
    label: 'OG card',
    kind: 'still',
    ratio: '40:21',
    px: {
      w: 1200,
      h: 630,
    },
    genre: 'card',
    maxBytes: 1048576,
    format: 'png',
    accepts: 'png|jpg',
    fit: 'cover',
    text: 'expected',
    safe: {
      x: 0.05,
      y: 0.0238,
      w: 0.9,
      h: 0.9524,
    },
    notes:
      'Text in the center ~1080×600. Set twitter:card=summary_large_image explicitly — og:image alone gets the small card.',
  },
  {
    id: 'github-social-preview',
    channel: 'github',
    asset: 'social-preview',
    label: 'GitHub social preview',
    kind: 'still',
    ratio: '2:1',
    px: {
      w: 1280,
      h: 640,
    },
    genre: 'card',
    maxBytes: 1048576,
    format: 'png',
    accepts: 'png|jpg',
    fit: 'cover',
    text: 'expected',
    safe: {
      x: 0.0391,
      y: 0.0781,
      w: 0.9219,
      h: 0.8438,
    },
    notes: 'Key text ≥50px from every edge.',
  },
]

export function destinationById(id: string): Destination | undefined {
  return DESTINATIONS.find((d) => d.id === id)
}

export function destinationsForChannel(channel: string): Destination[] {
  return DESTINATIONS.filter((d) => d.channel === channel)
}
