/**
 * The host <-> player bridge protocol — the one canonical contract between a host
 * (editor, player UI, export harness) and the playback document generated by
 * `generateRenderTemplate({ mode: 'playback' })`.
 *
 * Transport convention: SECONDS everywhere. `SEEK` (0-1 progress) is kept for
 * backward compatibility; new hosts use `SEEK_TIME`, and `UPDATE` carries
 * `time`/`duration` alongside the legacy `progress`.
 *
 * Editor-mode commands (`GET_ELEMENT_RECTS`, `HIT_TEST`, `SET_ELEMENT_PROPS`) are
 * only handled when the template was generated with `{ editor: true }` — the
 * production player pays nothing for them. `SET_ELEMENT_PROPS` is EPHEMERAL by
 * contract: it previews a gesture (drag/slider) on the live instance and does not
 * survive a `LOAD`; the durable edit is a config/document patch committed by the
 * host (a T3 warm swap on gesture release).
 */

/** Bumped whenever the message set changes. Advertised in `BRIDGE_READY`. */
export const VOS_BRIDGE_PROTOCOL = 8

/** One stack entry's live state, as `STACK_STATE` reports it. */
export interface StackEntryReport {
  id: string
  ok: boolean
  error: string | null
}

/** Element bounds in CSS pixels, relative to the player document's viewport. */
export interface ElementRect {
  id: string
  x: number
  y: number
  width: number
  height: number
  visible: boolean
}

/**
 * One entry of a tween-timing overlay — `@vosjs/tween`'s `TweenEdit`,
 * structurally: the recorded tween at `index`, retimed and/or revalued.
 */
export interface TweenEditPayload {
  index: number
  startTime?: number
  duration?: number
  ease?: string
  to?: Record<string, number>
  from?: Record<string, number>
}

/** Commands the host posts INTO the player document. */
export type VosBridgeCommand =
  /** Warm program (re)load — preserves transport across the swap. */
  | {
      type: 'LOAD'
      code?: string
      url?: string
      data?: Record<string, unknown> | null
      /** Per-entry data for the program stack, by entry id (overrides each entry's baked `data`). */
      stack?: Record<string, Record<string, unknown>> | null
      /** Protocol 8: a tween-timing overlay applied after init (see SET_TWEEN_EDITS). */
      tweenEdits?: TweenEditPayload[] | null
      autoplay?: boolean
    }
  /**
   * Live ctx.data replacement (T2) — no re-init. Protocol 5: `target` names a
   * stack entry, whose own data is replaced instead (its own three rungs).
   */
  | { type: 'SET_DATA'; data: Record<string, unknown>; target?: string }
  /** Protocol 5: the stack's live state (response: STACK_STATE). */
  | { type: 'GET_STACK_STATE'; requestId: number }
  /**
   * Protocol 6: mute or unmute every media element of the instance (video
   * and audio) without touching their gain or the transport. Survives a warm
   * LOAD. A compare pane, a muted preview, a second player on one page.
   */
  | { type: 'SET_MUTED'; muted: boolean }
  /**
   * Protocol 8: retime the running program's recorded tweens LIVE. The whole
   * overlay, every time (it applies from the recording, never on top of the
   * previous overlay); the frame at the current time repaints and an UPDATE
   * carries the new duration. Honored when the timeline can (`READY.
   * canRetimeTweens`: the vos tween backend); the gsap backend ignores it,
   * and a host then bakes the overlay into `createTimeline` and LOADs.
   */
  | { type: 'SET_TWEEN_EDITS'; edits: TweenEditPayload[] }
  | { type: 'PLAY' }
  | { type: 'PAUSE' }
  /** Legacy progress seek (0-1). Prefer SEEK_TIME. */
  | { type: 'SEEK'; value: number }
  /** Absolute seek in seconds (clamped to [0, duration]). */
  | { type: 'SEEK_TIME'; value: number }
  | { type: 'PLAY_SPEED'; value: number }
  /**
   * Retime the master timeline (T2.5) — only honored when the running program
   * supports it (see `READY.canSetDuration`); hosts otherwise fall back to LOAD.
   */
  | { type: 'SET_DURATION'; value: number }
  /** Editor mode: request bounds for all elements (response: ELEMENT_RECTS). */
  | { type: 'GET_ELEMENT_RECTS'; requestId: number }
  /** Editor mode: pick the topmost element at viewport CSS px (response: HIT_RESULT). */
  | { type: 'HIT_TEST'; x: number; y: number; requestId: number }
  /**
   * Editor mode: ephemeral element property override (via the props proxy).
   * Protocol 4: values may be strings — text raster props (content, font
   * family/style, colors) re-render the element's canvas in place.
   */
  | {
      type: 'SET_ELEMENT_PROPS'
      id: string
      props: Record<string, number | boolean | string>
    }
  /** Editor mode: ephemeral world-space object prop override (protocol 3). */
  | {
      type: 'SET_OBJECT_PROPS'
      id: string
      props: Record<string, number | boolean>
    }
  /** Editor mode: raycast declarative objects at viewport CSS px (response: OBJECT_HIT_RESULT). */
  | { type: 'OBJECT_HIT_TEST'; x: number; y: number; requestId: number }
  /**
   * Editor mode, protocol 6: the screen rect of one declarative object — its
   * world bounding box projected through the main camera into viewport CSS
   * px (response: OBJECT_RECT). The sibling of GET_ELEMENT_RECTS for the
   * 3D scene, so a host can draw a transform box around a prop.
   */
  | { type: 'OBJECT_BOUNDS'; id: string; requestId: number }

/** Events the player document posts OUT to the host. */
export type VosBridgeEvent =
  /** Document booted; bridge is listening. Feature-detect on `protocol`/`editor`. */
  | { type: 'BRIDGE_READY'; protocol: number; editor: boolean }
  /**
   * A program finished loading (assets ready, transport restored). Protocol 5:
   * `stack` lists the entry ids. Protocol 7: `retime` says the program carries
   * one — its transport is the output clock, and `canSetDuration` is true.
   */
  | {
      type: 'READY'
      duration: number
      canSetDuration: boolean
      stack: string[]
      retime: boolean
      /** Protocol 8: the timeline honors SET_TWEEN_EDITS. */
      canRetimeTweens: boolean
    }
  /** Protocol 5: a stack entry threw and is disabled for the session; everything else keeps running. */
  | { type: 'STACK_ERROR'; id: string; error: string }
  /** Response to GET_STACK_STATE. */
  | { type: 'STACK_STATE'; requestId: number; entries: StackEntryReport[] }
  /** Per-frame transport tick (driven by the timeline's onUpdate). */
  | { type: 'UPDATE'; progress: number; time: number; duration: number }
  | { type: 'ERROR'; error: string }
  /** Asset preload progress (posted by the element system during LOAD). */
  | { type: 'PRELOAD_PROGRESS'; loaded: number; total: number }
  | { type: 'HIT_RESULT'; requestId: number; id: string | null }
  /** Response to OBJECT_HIT_TEST — nearest declarative object along the ray. */
  | { type: 'OBJECT_HIT_RESULT'; requestId: number; id: string | null }
  /** Response to GET_ELEMENT_RECTS; also pushed with `requestId: null` on resize. */
  | { type: 'ELEMENT_RECTS'; requestId: number | null; rects: ElementRect[] }
  /** Response to OBJECT_BOUNDS; `rect` is null for an unknown or invisible object. */
  | {
      type: 'OBJECT_RECT'
      requestId: number
      id: string
      rect: ElementRect | null
    }
