/**
 * The host <-> player bridge protocol — the one canonical contract between a host
 * (editor, player UI, export harness) and the playback document generated by
 * `generateRenderTemplate({ mode: 'playback' })`.
 *
 * Transport convention: SECONDS everywhere. `SEEK` (0-1 progress) is kept for
 * backward compatibility; new hosts use `SEEK_TIME`, and `UPDATE` carries
 * `time`/`duration` alongside the legacy `progress`.
 *
 * Editor-mode commands (`GET_ELEMENT_RECTS`, `HIT_TEST`, `SET_ELEMENT_PROPS`) are
 * only handled when the template was generated with `{ editor: true }` — the
 * production player pays nothing for them. `SET_ELEMENT_PROPS` is EPHEMERAL by
 * contract: it previews a gesture (drag/slider) on the live instance and does not
 * survive a `LOAD`; the durable edit is a config/document patch committed by the
 * host (a T3 warm swap on gesture release).
 */

/** Bumped whenever the message set changes. Advertised in `BRIDGE_READY`. */
export const VOS_BRIDGE_PROTOCOL = 2

/** Element bounds in CSS pixels, relative to the player document's viewport. */
export interface ElementRect {
  id: string
  x: number
  y: number
  width: number
  height: number
  visible: boolean
}

/** Commands the host posts INTO the player document. */
export type VosBridgeCommand =
  /** Warm program (re)load — preserves transport across the swap. */
  | {
      type: 'LOAD'
      code?: string
      url?: string
      data?: Record<string, unknown> | null
      autoplay?: boolean
    }
  /** Live ctx.data replacement (T2) — no re-init. */
  | { type: 'SET_DATA'; data: Record<string, unknown> }
  | { type: 'PLAY' }
  | { type: 'PAUSE' }
  /** Legacy progress seek (0-1). Prefer SEEK_TIME. */
  | { type: 'SEEK'; value: number }
  /** Absolute seek in seconds (clamped to [0, duration]). */
  | { type: 'SEEK_TIME'; value: number }
  | { type: 'PLAY_SPEED'; value: number }
  /**
   * Retime the master timeline (T2.5) — only honored when the running program
   * supports it (see `READY.canSetDuration`); hosts otherwise fall back to LOAD.
   */
  | { type: 'SET_DURATION'; value: number }
  /** Editor mode: request bounds for all elements (response: ELEMENT_RECTS). */
  | { type: 'GET_ELEMENT_RECTS'; requestId: number }
  /** Editor mode: pick the topmost element at viewport CSS px (response: HIT_RESULT). */
  | { type: 'HIT_TEST'; x: number; y: number; requestId: number }
  /** Editor mode: ephemeral element property override (via the props proxy). */
  | {
      type: 'SET_ELEMENT_PROPS'
      id: string
      props: Record<string, number | boolean>
    }

/** Events the player document posts OUT to the host. */
export type VosBridgeEvent =
  /** Document booted; bridge is listening. Feature-detect on `protocol`/`editor`. */
  | { type: 'BRIDGE_READY'; protocol: number; editor: boolean }
  /** A program finished loading (assets ready, transport restored). */
  | { type: 'READY'; duration: number; canSetDuration: boolean }
  /** Per-frame transport tick (driven by the timeline's onUpdate). */
  | { type: 'UPDATE'; progress: number; time: number; duration: number }
  | { type: 'ERROR'; error: string }
  /** Asset preload progress (posted by the element system during LOAD). */
  | { type: 'PRELOAD_PROGRESS'; loaded: number; total: number }
  | { type: 'HIT_RESULT'; requestId: number; id: string | null }
  /** Response to GET_ELEMENT_RECTS; also pushed with `requestId: null` on resize. */
  | { type: 'ELEMENT_RECTS'; requestId: number | null; rects: ElementRect[] }
