/**
 * Generated by the vosso build; do not edit by hand.
 * Curation lives in the build script; re-run it (then `pnpm assets:push`) to
 * change the catalog. Files: https://assets.vos.so/fonts/{slug}/{weight}.woff2 (latin subset).
 */
export interface FontCatalogEntry {
  family: string
  slug: string
  category: 'sans' | 'serif' | 'display' | 'handwriting' | 'mono'
  /** Hosted weight steps — canvas cannot synthesize weights. */
  weights: number[]
}

export const FONT_CATALOG: FontCatalogEntry[] = [
  {
    family: 'Inter',
    slug: 'inter',
    category: 'sans',
    weights: [400, 500, 600, 700],
  },
  {
    family: 'Lexend',
    slug: 'lexend',
    category: 'sans',
    weights: [400, 600, 700],
  },
  {
    family: 'Roboto',
    slug: 'roboto',
    category: 'sans',
    weights: [400, 500, 700],
  },
  {
    family: 'Open Sans',
    slug: 'open-sans',
    category: 'sans',
    weights: [400, 600, 700],
  },
  {
    family: 'Montserrat',
    slug: 'montserrat',
    category: 'sans',
    weights: [400, 600, 700],
  },
  {
    family: 'Poppins',
    slug: 'poppins',
    category: 'sans',
    weights: [400, 500, 600, 700],
  },
  {
    family: 'Raleway',
    slug: 'raleway',
    category: 'sans',
    weights: [400, 600, 700],
  },
  {
    family: 'Work Sans',
    slug: 'work-sans',
    category: 'sans',
    weights: [400, 600, 700],
  },
  {
    family: 'Nunito',
    slug: 'nunito',
    category: 'sans',
    weights: [400, 600, 700],
  },
  {
    family: 'Rubik',
    slug: 'rubik',
    category: 'sans',
    weights: [400, 500, 700],
  },
  {
    family: 'DM Sans',
    slug: 'dm-sans',
    category: 'sans',
    weights: [400, 500, 700],
  },
  {
    family: 'Manrope',
    slug: 'manrope',
    category: 'sans',
    weights: [400, 600, 800],
  },
  {
    family: 'Outfit',
    slug: 'outfit',
    category: 'sans',
    weights: [400, 500, 700],
  },
  {
    family: 'Space Grotesk',
    slug: 'space-grotesk',
    category: 'sans',
    weights: [400, 500, 700],
  },
  {
    family: 'Plus Jakarta Sans',
    slug: 'plus-jakarta-sans',
    category: 'sans',
    weights: [400, 600, 700],
  },
  {
    family: 'Sora',
    slug: 'sora',
    category: 'sans',
    weights: [400, 600, 700],
  },
  {
    family: 'Figtree',
    slug: 'figtree',
    category: 'sans',
    weights: [400, 600, 700],
  },
  {
    family: 'Playfair Display',
    slug: 'playfair-display',
    category: 'serif',
    weights: [400, 600, 700],
  },
  {
    family: 'Merriweather',
    slug: 'merriweather',
    category: 'serif',
    weights: [400, 700, 900],
  },
  {
    family: 'Lora',
    slug: 'lora',
    category: 'serif',
    weights: [400, 500, 700],
  },
  {
    family: 'Libre Baskerville',
    slug: 'libre-baskerville',
    category: 'serif',
    weights: [400, 700],
  },
  {
    family: 'Cormorant Garamond',
    slug: 'cormorant-garamond',
    category: 'serif',
    weights: [400, 600, 700],
  },
  {
    family: 'EB Garamond',
    slug: 'eb-garamond',
    category: 'serif',
    weights: [400, 600, 700],
  },
  {
    family: 'DM Serif Display',
    slug: 'dm-serif-display',
    category: 'serif',
    weights: [400],
  },
  {
    family: 'Fraunces',
    slug: 'fraunces',
    category: 'serif',
    weights: [400, 600, 700],
  },
  {
    family: 'Source Serif 4',
    slug: 'source-serif-4',
    category: 'serif',
    weights: [400, 600, 700],
  },
  {
    family: 'Bebas Neue',
    slug: 'bebas-neue',
    category: 'display',
    weights: [400],
  },
  {
    family: 'Oswald',
    slug: 'oswald',
    category: 'display',
    weights: [400, 500, 700],
  },
  {
    family: 'Anton',
    slug: 'anton',
    category: 'display',
    weights: [400],
  },
  {
    family: 'Archivo Black',
    slug: 'archivo-black',
    category: 'display',
    weights: [400],
  },
  {
    family: 'Abril Fatface',
    slug: 'abril-fatface',
    category: 'display',
    weights: [400],
  },
  {
    family: 'Righteous',
    slug: 'righteous',
    category: 'display',
    weights: [400],
  },
  {
    family: 'Alfa Slab One',
    slug: 'alfa-slab-one',
    category: 'display',
    weights: [400],
  },
  {
    family: 'Caveat',
    slug: 'caveat',
    category: 'handwriting',
    weights: [400, 700],
  },
  {
    family: 'Pacifico',
    slug: 'pacifico',
    category: 'handwriting',
    weights: [400],
  },
  {
    family: 'Dancing Script',
    slug: 'dancing-script',
    category: 'handwriting',
    weights: [400, 700],
  },
  {
    family: 'Satisfy',
    slug: 'satisfy',
    category: 'handwriting',
    weights: [400],
  },
  {
    family: 'Shadows Into Light',
    slug: 'shadows-into-light',
    category: 'handwriting',
    weights: [400],
  },
  {
    family: 'JetBrains Mono',
    slug: 'jetbrains-mono',
    category: 'mono',
    weights: [400, 500, 700],
  },
  {
    family: 'Fira Code',
    slug: 'fira-code',
    category: 'mono',
    weights: [400, 500, 700],
  },
  {
    family: 'Space Mono',
    slug: 'space-mono',
    category: 'mono',
    weights: [400, 700],
  },
  {
    family: 'IBM Plex Mono',
    slug: 'ibm-plex-mono',
    category: 'mono',
    weights: [400, 500, 700],
  },
]
