/**
 * The ONE font-catalog seam (mirrors the params pattern): the curated,
 * self-hosted font families every surface reads — the FontField picker, the
 * take-editor lowering (SETUP FontFace loads), the API's GET /fonts, and
 * agent contracts. Generated by the vosso build; do not edit by hand. Files
 * live in the vosso-public bucket under fonts/ (assets.vos.so).
 */
import { FONT_CATALOG } from './fontCatalog'
import type { FontCatalogEntry } from './fontCatalog'

export { FONT_CATALOG } from './fontCatalog'
export type { FontCatalogEntry } from './fontCatalog'

export const FONT_CDN_BASE = 'https://assets.vos.so/fonts'

export type FontCategory = FontCatalogEntry['category']

/** Public URL of a hosted face file (latin subset, normal style). */
export function fontFaceUrl(slug: string, weight: number): string {
  return `${FONT_CDN_BASE}/${slug}/${weight}.woff2`
}

/** Case-insensitive family lookup. */
export function findFontFamily(family: string): FontCatalogEntry | undefined {
  const needle = family.trim().toLowerCase()
  return FONT_CATALOG.find((f) => f.family.toLowerCase() === needle)
}

/** Nearest hosted weight step (canvas cannot synthesize weights). */
export function nearestFontWeight(
  entry: FontCatalogEntry,
  weight: number,
): number {
  let best = entry.weights[0]
  for (const w of entry.weights) {
    if (Math.abs(w - weight) < Math.abs(best - weight)) best = w
  }
  return best
}

/**
 * CSS stack for a catalog family: the webfont first, then a category-true
 * system fallback (what renders during load and on fail-open).
 */
export function fontStack(entry: FontCatalogEntry): string {
  const quoted = entry.family.includes(' ') ? `'${entry.family}'` : entry.family
  const fallback =
    entry.category === 'serif'
      ? 'Georgia, serif'
      : entry.category === 'mono'
        ? 'ui-monospace, monospace'
        : entry.category === 'handwriting'
          ? 'cursive'
          : '-apple-system, system-ui, sans-serif'
  return `${quoted}, ${fallback}`
}

/** The manifest shape served by GET /api/fonts (mirrors fonts.json). */
export function fontManifest() {
  return {
    version: 1,
    base: FONT_CDN_BASE,
    families: FONT_CATALOG.map((e) => ({
      ...e,
      files: Object.fromEntries(
        e.weights.map((w) => [String(w), fontFaceUrl(e.slug, w)]),
      ),
    })),
  }
}
