/**
 * The ONE audio-catalog seam (mirrors the fonts pattern): the curated,
 * self-hosted music tracks and SFX every surface reads — the Audio panel
 * picker, the API's GET /music, and agent contracts. Generated by the vosso
 * build; do not edit by hand (curation + the CC0-only licensing rule live in
 * the build script); SFX are synthesized at build time, so their four
 * entries are stable literals here. Files live in the vosso-public bucket
 * (assets.vos.so) — docs store these absolute URLs (the backgrounds rule: a
 * ProjectDoc travels across environments, so keys must resolve everywhere).
 */
import { MUSIC_CATALOG } from './musicCatalog'
import type { MusicCatalogEntry } from './musicCatalog'

export { MUSIC_CATALOG } from './musicCatalog'
export type { MusicCatalogEntry } from './musicCatalog'

export const MUSIC_CDN_BASE = 'https://assets.vos.so/music'
export const SFX_CDN_BASE = 'https://assets.vos.so/audio-sfx'

export type MusicMood = MusicCatalogEntry['mood']

/** Display order + label for the mood chips (the product vocabulary). */
export const MUSIC_MOODS: { mood: MusicMood; label: string }[] = [
  { mood: 'upbeat', label: 'Upbeat' },
  { mood: 'minimal', label: 'Minimal' },
  { mood: 'chill', label: 'Chill' },
  { mood: 'groove', label: 'Groove' },
  { mood: 'cinematic', label: 'Cinematic' },
]

export interface SfxCatalogEntry {
  slug: string
  title: string
  duration: number
}

/** Built-in SFX (synthesized by the vosso build, CC0). */
export const SFX_CATALOG: SfxCatalogEntry[] = [
  { slug: 'sfx-click', title: 'Click', duration: 0.07 },
  { slug: 'sfx-pop', title: 'Pop', duration: 0.12 },
  { slug: 'sfx-whoosh', title: 'Whoosh', duration: 0.6 },
  { slug: 'sfx-chime', title: 'Chime', duration: 1.4 },
]

/** Public URL of a hosted music track (−16 LUFS normalized MP3). */
export function musicTrackUrl(slug: string): string {
  return `${MUSIC_CDN_BASE}/${slug}.mp3`
}

/** Public URL of a built-in SFX file. */
export function sfxUrl(slug: string): string {
  return `${SFX_CDN_BASE}/${slug}.wav`
}

/** Look a track up by slug or by its hosted URL (for UI labels). */
export function findMusicTrack(
  slugOrUrl: string,
): MusicCatalogEntry | undefined {
  const slug = slugOrUrl.startsWith(MUSIC_CDN_BASE)
    ? slugOrUrl.slice(MUSIC_CDN_BASE.length + 1).replace(/\.mp3$/, '')
    : slugOrUrl
  return MUSIC_CATALOG.find((t) => t.slug === slug)
}

/** The manifest shape served by GET /api/music (mirrors music.json + SFX). */
export function musicManifest() {
  return {
    version: 1,
    base: MUSIC_CDN_BASE,
    tracks: MUSIC_CATALOG.map((t) => ({ ...t, url: musicTrackUrl(t.slug) })),
    sfx: SFX_CATALOG.map((s) => ({ ...s, url: sfxUrl(s.slug) })),
  }
}
