/**
 * Generated by the vosso build; do not edit by hand.
 * Curation (and the CC0-only licensing rule) lives in the build script;
 * re-run it (then `pnpm assets:push`) to change the catalog.
 * Files: https://assets.vos.so/music/{slug}.mp3 (−16 LUFS normalized).
 */
export interface MusicCatalogEntry {
  slug: string
  title: string
  artist: string
  mood: 'upbeat' | 'minimal' | 'chill' | 'groove' | 'cinematic'
  /** Track length in seconds (probed from the normalized file). */
  duration: number
  license: 'CC0'
}

export const MUSIC_CATALOG: MusicCatalogEntry[] = [
  {
    slug: 'fresh-focus',
    title: 'Fresh Focus',
    artist: 'Kevin MacLeod',
    mood: 'upbeat',
    duration: 124.1,
    license: 'CC0',
  },
  {
    slug: 'motions',
    title: 'Motions',
    artist: 'Rafael Krux',
    mood: 'upbeat',
    duration: 117,
    license: 'CC0',
  },
  {
    slug: 'and-just-like-that',
    title: 'And Just Like That',
    artist: 'Bryan Teoh',
    mood: 'upbeat',
    duration: 114.3,
    license: 'CC0',
  },
  {
    slug: 'arpent',
    title: 'Arpent',
    artist: 'Kevin MacLeod',
    mood: 'minimal',
    duration: 162.1,
    license: 'CC0',
  },
  {
    slug: 'beat-one',
    title: 'Beat One',
    artist: 'Kevin MacLeod',
    mood: 'minimal',
    duration: 180,
    license: 'CC0',
  },
  {
    slug: 'meditating-beat',
    title: 'Meditating Beat',
    artist: 'Kevin MacLeod',
    mood: 'chill',
    duration: 157.2,
    license: 'CC0',
  },
  {
    slug: 'study-and-relax',
    title: 'Study and Relax',
    artist: 'Kevin MacLeod',
    mood: 'chill',
    duration: 223.4,
    license: 'CC0',
  },
  {
    slug: 'starcourt-mall',
    title: 'Starcourt Mall',
    artist: 'Bryan Teoh',
    mood: 'chill',
    duration: 217.5,
    license: 'CC0',
  },
  {
    slug: 'gotta-keep-on-movin',
    title: 'Gotta Keep On Movin',
    artist: 'Bryan Teoh',
    mood: 'groove',
    duration: 144,
    license: 'CC0',
  },
  {
    slug: 'hold-on-a-sec',
    title: 'Hold on a Sec',
    artist: 'Bryan Teoh',
    mood: 'groove',
    duration: 125.5,
    license: 'CC0',
  },
  {
    slug: 'slice-of-life',
    title: 'Slice of Life',
    artist: 'Bryan Teoh',
    mood: 'cinematic',
    duration: 140.8,
    license: 'CC0',
  },
  {
    slug: 'ice-and-snow',
    title: 'Ice and Snow',
    artist: 'Rafael Krux',
    mood: 'cinematic',
    duration: 141.5,
    license: 'CC0',
  },
]
