/**
 * Generated by the vosso build; do not edit by hand.
 * Curation lives in the build script; regenerate + `pnpm assets:push`, then
 * commit this file. One catalog: the 3D prop panel, take lowering, and the
 * CLI lints all read it.
 */

export interface TypefaceEntry {
  /** Catalog family name (matches the webfont catalog). */
  family: string
  /** File slug — typefaces/{slug}.typeface.json on assets.vos.so. */
  slug: string
  /** The converted weight (one file per family; extrusion wants bold). */
  weight: number
}

export const TYPEFACE_CDN_BASE = 'https://assets.vos.so/typefaces'

/** The house default 3D face. */
export const DEFAULT_TYPEFACE_SLUG = 'lexend'

export const TYPEFACE_CATALOG: TypefaceEntry[] = [
  { family: 'Lexend', slug: 'lexend', weight: 700 },
  { family: 'Space Grotesk', slug: 'space-grotesk', weight: 700 },
  { family: 'Bebas Neue', slug: 'bebas-neue', weight: 400 },
  { family: 'Archivo Black', slug: 'archivo-black', weight: 400 },
  { family: 'Anton', slug: 'anton', weight: 400 },
  { family: 'Righteous', slug: 'righteous', weight: 400 },
  { family: 'Playfair Display', slug: 'playfair-display', weight: 700 },
  { family: 'Fraunces', slug: 'fraunces', weight: 700 },
  { family: 'Pacifico', slug: 'pacifico', weight: 400 },
  { family: 'JetBrains Mono', slug: 'jetbrains-mono', weight: 700 },
]

export function typefaceUrl(slug: string): string {
  return `${TYPEFACE_CDN_BASE}/${slug}.typeface.json`
}

/** Case-insensitive lookup by slug or family name (null = not in catalog). */
export function findTypeface(nameOrSlug: string): TypefaceEntry | null {
  const needle = nameOrSlug.trim().toLowerCase()
  return (
    TYPEFACE_CATALOG.find(
      (t) => t.slug === needle || t.family.toLowerCase() === needle,
    ) ?? null
  )
}
